package login;

import addcomponent.SpringUtilities;
import connection.c_connection_pass;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SpringLayout;
import static login.F_Login_initialization.Registerbtn;
import static login.F_Login_initialization.back;
import static login.F_Login_initialization.l_a_p;
import static login.F_Login_initialization.l_a_product;
import static login.F_Login_initialization.l_a_product_valid_email;
import static login.F_Login_initialization.textField_1;
import static login.F_Login_initialization.textField_2;
import static login.F_Login_initialization.textField_3;
import static login.F_Login_initialization.textField_4;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jude
 */
public class F_register extends javax.swing.JFrame {
JPanel hai_origin = new JPanel();
     
/**
     * Creates new form MainFrame
     */
    public F_register() {
        init_label();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void init_label(){
        F_Login_initialization.l_a_p.setVisible(false);
        F_Login_initialization.l_a_p.setForeground(Color.yellow);
        F_Login_initialization.l_a_product.setVisible(false);
        F_Login_initialization.l_a_product.setForeground(Color.yellow);
        l_a_product_valid_email.setVisible(false);
        l_a_product_valid_email.setForeground(Color.yellow);
    }
    
    private void init_back(){
        
    }
    
      public JPanel init_(){
        
            SpringLayout layout = new SpringLayout();
                        hai_origin.setLayout(layout);
           hai_origin.setPreferredSize(new Dimension(325,350));
           hai_origin.setBounds(0, 0, hai_origin.getWidth(), hai_origin.getHeight());
          // hai_origin.setBackground(new Color(255,255,255,10));
           
           JLabel Title = new JLabel("Welcome Pendeta, Only Register Once", JLabel.TRAILING);
           Title.setForeground(Color.WHITE);
       
           JPanel hai2 = new JPanel(new GridLayout(8, 1, 5, 5));
           hai2.setPreferredSize(new Dimension(300,300));
           hai2.setBounds(0, 0, hai2.getWidth(), hai2.getHeight());
        
   
           // Email field
           JLabel l = new JLabel("Email", JLabel.LEADING);
           hai2.add(l);
           textField_1.setPreferredSize(new Dimension(hai2.getWidth(), 30));
           hai2.add(textField_1);
           
           // Password field
           JLabel l_2 = new JLabel("Password", JLabel.LEADING);
        
           hai2.add(l_2);
           textField_2.setPreferredSize(new Dimension(hai2.getWidth(), 30));
           hai2.add(textField_2);
           
           // Retype field
           JLabel l_2_2 = new JLabel("Retype", JLabel.LEADING);
        
           hai2.add(l_2_2);
           textField_3.setPreferredSize(new Dimension(hai2.getWidth(), 30));
           hai2.add(textField_3);
           
           // Product ID field
           JLabel l_2_2_2 = new JLabel("Product Id", JLabel.LEADING);
          
           hai2.add(l_2_2_2);
           textField_4.setPreferredSize(new Dimension(hai2.getWidth(), 30));
           hai2.add(textField_4);
           
           // Style the Register and Back buttons
           Dimension buttonSize = new Dimension(200, 35);
           Registerbtn.setPreferredSize(buttonSize);
           back.setPreferredSize(buttonSize);
           
           // Add separator with "or" text
           JLabel separator = new JLabel("---------------------or-----------------------", JLabel.CENTER);
           separator.setForeground(Color.WHITE);
           
           layout.putConstraint(SpringLayout.VERTICAL_CENTER, Title, -200, SpringLayout.VERTICAL_CENTER, hai_origin);  
           layout.putConstraint(SpringLayout.HORIZONTAL_CENTER, Title, 0, SpringLayout.HORIZONTAL_CENTER, hai_origin); 
           layout.putConstraint(SpringLayout.VERTICAL_CENTER, hai2, -35, SpringLayout.VERTICAL_CENTER, hai_origin);  
           layout.putConstraint(SpringLayout.HORIZONTAL_CENTER, hai2, 0, SpringLayout.HORIZONTAL_CENTER, hai_origin); 
           layout.putConstraint(SpringLayout.VERTICAL_CENTER, Registerbtn, 150, SpringLayout.VERTICAL_CENTER, hai_origin);  
           layout.putConstraint(SpringLayout.HORIZONTAL_CENTER, Registerbtn, 0, SpringLayout.HORIZONTAL_CENTER, hai_origin); 
           layout.putConstraint(SpringLayout.VERTICAL_CENTER, separator, 180, SpringLayout.VERTICAL_CENTER, hai_origin);
           layout.putConstraint(SpringLayout.HORIZONTAL_CENTER, separator, 0, SpringLayout.HORIZONTAL_CENTER, hai_origin);
           layout.putConstraint(SpringLayout.VERTICAL_CENTER, back, 210, SpringLayout.VERTICAL_CENTER, hai_origin);  
           layout.putConstraint(SpringLayout.HORIZONTAL_CENTER, back, 0, SpringLayout.HORIZONTAL_CENTER, hai_origin); 
           layout.putConstraint(SpringLayout.VERTICAL_CENTER, l_a_p, 160, SpringLayout.VERTICAL_CENTER, hai_origin);  
           layout.putConstraint(SpringLayout.HORIZONTAL_CENTER, l_a_p, -60, SpringLayout.HORIZONTAL_CENTER, hai_origin);           
           layout.putConstraint(SpringLayout.VERTICAL_CENTER, l_a_product, 190, SpringLayout.VERTICAL_CENTER, hai_origin);  
           layout.putConstraint(SpringLayout.HORIZONTAL_CENTER, l_a_product, -60, SpringLayout.HORIZONTAL_CENTER, hai_origin);           
           layout.putConstraint(SpringLayout.VERTICAL_CENTER, l_a_product_valid_email, 220, SpringLayout.VERTICAL_CENTER, hai_origin);  
           layout.putConstraint(SpringLayout.HORIZONTAL_CENTER, l_a_product_valid_email, -60, SpringLayout.HORIZONTAL_CENTER, hai_origin);           
                        
            
            hai_origin.add(Title);
            hai_origin.add(hai2);
            hai_origin.add(Registerbtn);
            hai_origin.add(separator);
            hai_origin.add(back);
             hai_origin.add(l_a_p);  
             hai_origin.add(l_a_product);
             hai_origin.add(l_a_product_valid_email);
             
     
            return hai_origin;
    }
    
    

    
    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
 
    }                                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginbtn;
    private javax.swing.JTextField uname;
    private javax.swing.JTextField upass;
    // End of variables declaration                   
}
